### ISSUE TITLE
Can't connect to the switch with AsyncSSH with "auth_strict_key" = False option

### ISSUE THREAD

**Issue by davaeron** [carlmontanari/scrapli#173]
**Describe the bug**
 When you have in Scrapli connection options "auth_strict_key" = False for AsyncSSH transport, there is a known bug for AsyncSSH with "known_hosts"=None https://github.com/ronf/asyncssh/issues/323
When that happens AsyncSSH send all his "host_key_algs" to the host and that's more than 20 of them and there are some hosts that just disconnects on such a many number of host keys algs received.

**To Reproduce**
1. When you have in connection options for AsyncSSH tranport "auth_strict_key" = False
```
conn_dict["auth_strict_key"] = False
conn = AsyncGenericDriver(**conn_dict)
```
2. Your switch can't comprehend so much "host_key_algs" sent at him.
3. Switch closes connection on key exchange.

**Expected behavior**
Scrapli connects through AsyncSSH.

**How to fix**
So, as a workaround i added "server_host_key_algs=['ssh-rsa']" to 
scrapli\transport\plugins\asyncssh\transport.py lines 113-127
```
        try:
            self.session = await asyncio.wait_for(
                connect(
                    client_keys=self.plugin_transport_args.auth_private_key,
                    password=self.plugin_transport_args.auth_password,
                    preferred_auth=(
                        "publickey",
                        "keyboard-interactive",
                        "password",
                    ),
                    server_host_key_algs=['ssh-rsa'],
                    **common_args,
                ),
                timeout=self._base_transport_args.timeout_socket,
            )
```
It works for me now, but i think for the general Scrapli use it must some more clever solution.
Something like:
1. Check if "auth_strict_key" is False.
2. Add "server_host_key_algs=['ssh-rsa']" to the list of AsyncSSH transport options.

**OS (please complete the following information):**
 - OS: Debian 10.7
 - scrapli version: 2021.07.30

**Comment by carlmontanari** [comment]
@davaeron thanks for raising this and bringing a solution! I will take a peak this weekend and see how we can get this added in nicely! 

Carl

**Comment by carlmontanari** [comment]
Hey @davaeron -- just pushed a draft at a fix.

I think it seems like it may be "risky" to only send ssh-rsa since we cant really know what the servers will accept, so I just thinned down the list that asyncssh wants to send to the ones that look the most popular to me (sorta a swag to be honest since I actually don't really know which ones are the most popular... mostly I removed the cert ones and stuff that I haven't seen pop up often). We can then use a `transport_options` setting `limit_key_algorithms` --> `True` will cause us to just send this thinned down list. The list is global so users can modify that if they need to as well. 

So something like this should work for you now:

```
conn1 = AsyncIOSXEDriver(
    host="c3560",
    transport="asyncssh",
    ssh_config_file=True,
    auth_strict_key=False,
    port=22,
    transport_options={"limit_key_algorithms": True}
)
```

This is in the branch `asyncssh-too-many-key-algos` which you can install like: 

`pip install -e git+https://github.com/carlmontanari/scrapli.git@ asyncssh-too-many-key-algos#egg=scrapli`

If you have a sec could you give that a try and let us know if this fixes the issue for you? Also, do you think this is a good solution in general?

Thanks a ton!

Carl

**Comment by davaeron** [comment]
@carlmontanari Carl, looks like i've found a solution that will not require any code changes.
I've used custom ssh_config with:
```
Host *
HostKeyAlgorithms ssh-rsa
```
added it to
conn_dict["ssh_config_file"] = "my_ssh_config"
and it works!
I think that you don't need to change any code and just include this into Scrapli "Known bugs" section with this workaround.

**Comment by carlmontanari** [comment]
> looks like i've found a solution that will not require any code changes 

I like the way you think! 😁 

I will leave this open to make sure I remember to document this this weekend! Thanks again for all the help!

Carl

**Comment by carlmontanari** [comment]
Since I got rid of the "known issues" section a while back since (thankfully) there were not many, and also because I kept forgetting about it and so it was never updated/contained outdated things... I just added this to the transport plugin docstrings. Hopefully that ++ this issue will make this searchable enough for folks in the future!

Thanks again for your work on this!

Carl
