### ISSUE TITLE
Question: Certificate / Key Based Authentication

### ISSUE THREAD

**Issue by AuthenticAMD** [carlmontanari/scrapli#298]
Looking at the previous bug reports, it looks like the asyncssh plugin was setting the agent_path to None, and thus breaking ssh-agent forwarding.

I've think I've implemented the proper syntax to do agent forwarded authentication via keys, but it doesn't seem to work. Below is a configured profile for connecting. Is there something wrong, or even better, an example of agent based authentication?

`
ASR = {
'host': "1.1.1.1",
'auth_username': 'testing',
'auth_password': '',
'auth_strict_key': False,
'transport': 'asyncssh',
'transport_options': {'agent_path': () },
'driver': AsyncIOSXEDriver
}
`

**Comment by carlmontanari** [comment]
offhand I think you are missing `asyncssh` in transport options -> `{"transport_options": {"asyncssh": {stuff}}` -- maybe ya can give that a shot and/or if you have an example of what works w/ asyncssh directly would be easy to see how we can plug it in here. im just looking [here](https://github.com/carlmontanari/scrapli/blob/main/scrapli/transport/plugins/asyncssh/transport.py#L60-L68) since I dont know for sure :D -- wanna try that and let us know if that helps?

**Comment by AuthenticAMD** [comment]
That is fair. I've added your option below, and it doesn't seem to work? Note, I have to re-dictate the code below, so it may have some typos.

`
import json
import asyncio
import sys
import getpass
from scrapli.driver.core import AsyncIOSXEDriver, AsyncNXOSDriver

ASR = { 'host': '1.1.1.1', 'auth_username': 'testing', 'auth_password': '', 'auth_strict_key': False, 'transport': 'asyncssh', 'transport_options': {'asyncssh': {'agent_path': () }}, 'driver': AsyncIOSXEDriver }

N9K = { 'host': '1.1.1.2', 'auth_username': 'testing', 'auth_password': '', 'auth_strict_key': False, 'transport': 'asyncssh', 'transport_options': {'asyncssh': {'agent_path': () }}, 'driver': AsyncNXOSDriver }

DEVICES = [ASR,N9K]

async def fetch_data(device):
   driver = device.pop("driver")
   async with driver(**device) as conn:
      responses = await conn.send_commands(["show ip int brief", "show version"])
      return responses

async def main():
   coroutines = [fetch_data(device) for device in DEVICES]
   results = await asyncio.gather(*coroutines)
   for result in results:
      print(result.result)

if __name__ == "__main__":

   USERNAME = input("Enter username: ")
   while True:
      password = getpass.getpass(prompt="Password: ")
      password2 = getpass.getpass(prompt="Repeat Password: ")
      if password == password2:
        PASSWORD = password
        break

   for key, value in ASR.items():
      ASR["auth_username"] = USERNAME
      ASR["auth_password"] = PASSWORD
   for key, value in N9K.items():
      N9K["auth_username"] = USERNAME
      N9K["auth_password"] = PASSWORD

   asyncio.run(main())
`

**Comment by carlmontanari** [comment]
do you have a working example w/ asyncssh? quickly searching looks like you may need to actually specify the path there *or* have the env var set to define it. copy/pasta from asyncssh docs:

```
agent_path (str) – (optional) The path of a UNIX domain socket to use to contact an ssh-agent process which will perform the operations needed for client public key authentication, or the SSHServerConnection to use to forward ssh-agent requests over. If this is not specified and the environment variable SSH_AUTH_SOCK is set, its value will be used as the path. If this argument is explicitly set to None, an ssh-agent will not be used.
```

**Comment by AuthenticAMD** [comment]
If you're asking if I have a working example using asyncssh and key based auth, then no. The example above is a working example with password based auth.

I saw that section you're referencing previously. SSH_AUTH_SOCK is set as if I echo it, then I get a value. ssh-add -L also confirms the agent is functioning and regular ssh to device works with key based auth. However I've been trying different permutations, such as excluding the transport_options section, including it with the agent_path undefined without success.

**Comment by carlmontanari** [comment]
I think you just need to get this working w/ asyncssh; then it will be very easy to make work w/ scrapli as we are literally just passing the options directly to asyncssh. you can try to actually set the agent path explicitly I guess. you could try to specify keys directly too to make sure everything works without the agent bits.

I'm going to close this though as I dont think there is any scrapli related issue here. if you have a working example w/ asyncssh and that doesn't/can't be made to work w/ scrapli, or there is some scrapli specific issue here then defo reopen, but I dont *think* (always subject to being proven wrong!) thats the case since im pretty sure this was all put to bed in #266/#268

**Comment by AuthenticAMD** [comment]
Just getting back from vacation. I apparently didn't know what you were asking. But here is a working example with asyncssh using keys.

```
import asyncio, asyncssh, sys

async def run_client() -> None:
    async with asyncssh.connect('10.1.1.1') as conn:
        result = await conn.run('ls abc', check=True)
        print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

**Comment by AuthenticAMD** [comment]
OK, found the problem. Apparently for one of the two devices that I didn't update the transport options like you've stated. If looks like I'll have to provide some error handling in that case so that devices that work will come back and devices that don't will fail gracefully.
