### ISSUE TITLE
Question: are custom/third-party transports supported?

### ISSUE THREAD

**Issue by mvenditto** [carlmontanari/scrapli#327]
Hi, 
We're using scrapli in production to collect configurations from several hundred of devices.
Due to some constraints/requirements we need implement a custom transport.

Is it possible to add a custom transport?

The readme states the following:
> scrapli provides a pluggable transport system -- don't like the currently available transports, simply extend the base classes and add your own!

Is it still a possibility and we're missing something or it was referring to when some transport were loaded as plugins, before being rolled back to scrapli "core"?

From what I can see it seem the pluggable transport system is still in place but the *transport name* is checked against known transport names (eg. from `scrapli.transport.ASYNCIO_TRANSPORTS`), making it not possible to load third-party transports.

Thanks in advance!

**Comment by carlmontanari** [comment]
ciao 👋 

it "should" work I think but... its defo been years since I tested it :) `_load_non_core_transport_plugin` in base driver is what you are looking for I think. this method tries to use import lib to load a package `f"scrapli_{self.transport_name}.transport"` -- after that there is some getattr stuff to fetch the actual transport class and the transport args then things should work from there. obviously this assumes your transport satisfies the ultra simple transport base abstract classes (this could/should be nicer w/ a protocol but... probably you will be the only one using this :P). 

alternatively you could always just extend the base driver class yourself to always load your transport and then monkey patch that over scrapli -- doing some hand waving here, but that general idea should work just fine if you wanted to go that route.

**Comment by mvenditto** [comment]
Thanks for the tips!

> 
> it "should" work I think but... its defo been years since I tested it :) `_load_non_core_transport_plugin` in base driver is what you are looking for I think. this method tries to use import lib to load a package `f"scrapli_{self.transport_name}.transport"` -- after that there is some getattr stuff to fetch the actual transport class and the transport args then things should work from there. obviously this assumes your transport satisfies the ultra simple transport base abstract classes (this could/should be nicer w/ a protocol but... probably you will be the only one using this :P).

I experimented a bit with the plugin transport approach but it works only if using an `sync` driver.
In the `async` scenario it throws an error because there is a check to verify that the *transport name*  is in `scrapli.transport.ASYNCIO_TRANSPORTS`; the check is in both [factory](https://github.com/carlmontanari/scrapli/blob/5c4e7bc97e61bb21bf2706a5bf76a8b60b197091/scrapli/factory.py#L767) and [async_driver](https://github.com/carlmontanari/scrapli/blob/5c4e7bc97e61bb21bf2706a5bf76a8b60b197091/scrapli/driver/base/async_driver.py#L18).
The other way around works because the check is reversed.

>
> alternatively you could always just extend the base driver class yourself to always load your transport and then monkey patch that over scrapli -- doing some hand waving here, but that general idea should work just fine if you wanted to go that route.

I'll try this option too.

Grazie!

**Comment by carlmontanari** [comment]
> In the async scenario it throws an error because there is a check to verify that the transport 

ahhhh ok ok I got ya! yeah we can for sure fix that up too. up for a pr for it? we can just do the ASYNCIO_TRANSPORTS check for "core" stuff and not check if we are using some custom transport.

**Comment by carlmontanari** [comment]
resolved by #329 grazie ancora!
