### ISSUE TITLE
Instantiate driver based on driver string

### ISSUE THREAD

**Issue by afourmy** [carlmontanari/scrapli#35]
With a multi-vendor inventory, we would usually have the device type as a string such as `ios` or `eos`.  In netmiko, this works well because we pass the driver as a string to `ConnectHandler` but it seems that in scrapli, the only way is to explicitly import all drivers from `scrapli.driver.core` (without using a workaround like `__import__`).

With the current code it doesn't seem straightforward to add a `driver` key like in netmiko, but is there (or could there be) something like netmiko `CLASS_MAPPER` (https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_dispatcher.py#L98-L197) that associates driver names to their class so that we can instantiate a driver programmatically (`with MAPPER[driver_name](**device) as...`) ?

**Comment by carlmontanari** [comment]
Hi @afourmy 

This will be added sometime soon, but you are correct that this currently does not exist. You can easily do this yourself for now like so:

```python
from scrapli.driver.core import (                                                                                                    
    IOSXEDriver,
    IOSXRDriver,
    NXOSDriver,
    EOSDriver,
    JunosDriver,
)

driver_map = {
    "cisco_iosxe": IOSXEDriver,
    "cisco_iosxr": IOSXRDriver,
    "cisco_nxos": NXOSDriver,
    "arista_eos": EOSDriver,
    "juniper_junos": JunosDriver,
}

my_example_host_inventory = {
    "platform": "cisco_iosxe",
    "auth_username": "vrnetlab",
    "auth_password": "VR-netlab9",
    "host": "172.31.254.1",
}

driver = driver_map.get(my_example_host_inventory.pop("platform"))
conn = driver(**my_example_host_inventory)
conn.open()
print(conn.get_prompt())
conn.close()
```

I hope/think that I'll be adding this in the next release (within a months time), and it will likely look something like:

```
from scrapli import Scrapli

my_example_host_inventory = {
    "platform": "cisco_iosxe",
    "auth_username": "vrnetlab",
    "auth_password": "VR-netlab9",
    "host": "172.31.254.1",
}

conn = Scrapli(**my_example_host_inventory)
```

However there are few things I want to be very sure that I address/points worth understanding:

1. Typing/inheritance -- the `Scrapli` object must inherit from the `NetworkDriver` so that all IDE auto complete/intelisense/typing pieces work and understand the methods available to the instantiated object of the `Scrapli` class.
2. This likely means there will be a `Scrapli` and a `AsyncScrapli` class -- obviously depending on sync vs asyncio!
3. I want to figure out a smart way to support users adding "non core" platforms without having a billion device types/classes. I also want there to not need to be different versions of a given "driver"/platform  -- i.e I don't want to see "cisco iosxe" and "cisco ios" for example. This is probably even more noticeable for things like Aruba/Nokia that have had different acquisitions and changes to the OSes over time. All of this is probably the hardest part and will require some time.
4. I need to create a "scrapli_community" repo where users can contribute different platform info (in some nice way so that point3 does not become a nightmare). This will all live in a separate repo to keep scrapli "core" maintenance burden down as low as possible.

Sorry, I know that does not really address the current issue, but wanted to let you know that something like this *is* coming and give a little context for it.

I'd be keen to get any feedback/ideas/thoughts you have on the matter (especially pertaining to the community driver part), so please feel free to drop that here.

Carl

**Comment by afourmy** [comment]
Hello @carlmontanari 

Thanks for the detailed answer ! I'll create the driver mapping myself for now until this next release. I think the community driver repo is a great idea, it worked well for napalm.

**Comment by carlmontanari** [comment]
@afourmy While I haven't made any progress on the "community" side of things, I did get a proof of concept of the factory/class picker pushed to develop.

You can find this in `scrapli/factory.py`, and you can test it out like so:

```
from scrapli import Scrapli


device = {
    "host": "172.31.254.1",
    "auth_strict_key": False,
    "ssh_config_file": True,
    "platform": "cisco_iosxe"
}

conn = Scrapli(**device)
conn.open()
print(conn.get_prompt())
conn.close()
```

Where `platform` is one of the core driver types -- "cisco_iosxe", "cisco_iosxr", "cisco_nxos", "arista_eos", or "juniper_junos".

I'll probably spend tomorrow working on sketching out the "community" stuff in more detail. If you want to test this out you can do so by installing the develop branch like so:

```
pip install -e git+https://github.com/carlmontanari/scrapli.git@develop#egg=scrapli
```

There will also (probably tomorrow) be a `AsyncScrapli` class that will work the same, except it will only return async drivers. This "regular" `Scrapli` will probably also get some handling to ensure that users don't pass async transport plugins to this. The reason for the two different factories is to ensure that type hinting/intelisense stuff all makes sense -- so that when you have an async driver PyCharm/VSCode/whatever can know that you have received an async driver from the factory.

I'd love to hear any feedback on this!

Carl

**Comment by afourmy** [comment]
@carlmontanari I just tested and it works fine. Thanks !

**Comment by carlmontanari** [comment]
Hi again @afourmy 

I've just pushed a new release to pypi with the `Scrapli` and `AsyncScrapli` factory classes. This should behave just as outlined in the previous post. I've also created the first draft of the scrapli_community repo (though it is not on PyPi just yet), you can find that [here](https://github.com/scrapli/scrapli_community). For now this just has a few example "platforms" that are only really used for testing scrapli core, and a first draft of a Huawei VRP platform that I built from some info in past issues. The Huawei stuff is not tested but would hopefully work, and hopefully soon some folks will check that out and get it updated to work as desired!

I'm going to go ahead and close this now, but feel free to reopen if the factory classes are not working as expected.

Thanks again for raising this!

Carl
