### ISSUE TITLE
Logging session to a file

### ISSUE THREAD

**Issue by egreenspan2** [carlmontanari/scrapli#70]
Hello, 

I am looking for an option to log a scrapli "session" to a file for debugging/monitoring, this would be similar to netmiko "session_log" connection option.

I can't seem to find this in the docs, I am missing it or maybe its not implemented.

I can obviously gather the data if I turn up the logging level to INFO, but its not in a user friendly format for average network engineer.

BTW, thank you for this excellent tool, works so much better and more consistent than netmiko with nornir.

**Comment by carlmontanari** [comment]
Hey @egreenspan2 ! Glad you are enjoying scrapli :D 

Nothing exactly like that exists. As you pointed out logging w/ INFO is probably as close as you can get right now....

Another thing that may be handy is that response object contains the `channel_input` and of course the `result` (though for configuration this is almost always just empty new lines because there is no "output" from configuring a name server or whatever) -- so you can fairly easily "reconstruct" what was sent/received.

All that said this is actually something I've been thinking about a bit lately -- making some way to "replay" a session... in other words show all the inputs/outputs as a "normal" person would have seen if they were on the the terminal. That said its just a bit of a dream at the moment and is probably fairly low priority. PRs are always welcome though I would probably be fairly particular w/ how this could/would be implemented.

**Comment by egreenspan2** [comment]
Thank you for the feedback, I just wanted to make sure I am not missing something when I was reading the docs.  Will have to stick with logging level for now, granted this is a low priority item, just got spoiled by session_log and ease of tracing what happened during the interaction with the device.

**Comment by carlmontanari** [comment]
I'm going to go ahead and close this out as there isn't anything to do on this right at this moment. Thanks for opening this though, and def feel free to play around and open a PR if you want to take a crack at implementing this. Hit me up on (networktocode) slack if you wanna chat about it more!

Carl

**Comment by carlmontanari** [comment]
Hey @egreenspan2 -- if you are still keen on channel log, check out the `overhaul` branch -- add the argument `channel_log` as `True` or a string path to where you want the log file to be written and you will get logging output like you are looking for :)

Driver args docs updated [here](https://carlmontanari.github.io/scrapli/api_docs/driver/base_driver/)

Carl

**Comment by egreenspan2** [comment]
I will try this out asap! Finally back from vacation :), thanks you so much!  This is a much desired feature
