### ISSUE TITLE
Timeout_ops for send_interactive

### ISSUE THREAD

**Issue by egreenspan2** [carlmontanari/scrapli#71]
Carl,

Is there a "easy" way to adjust the timeout_ops for send_interactive function?  Using this functionality to execute code upgrades on switches which can run for a <very> long time and require prompt answers.  Setting the timeout_ops globally is an option, I suppose, but it would be nice to control that per command.

**Comment by carlmontanari** [comment]
You have great timing haha. Was just thinking about this the other day myself.... lemme see if I can easily bolt that kwarg `timeout_ops` into `send_interactive` the same way I did for the "normal" command/config operations. Will keep ya posted!

**Comment by egreenspan2** [comment]
My simple "workaround" is setting 
`task.host.connections['scrapli'].connection.channel.timeout_ops = timeout`

before calling 
`task.run( task=send_interactive, interact_events=commands)`

and resetting it back after.

**Comment by carlmontanari** [comment]
Yep, hopefully that'll hold ya over for a bit, will keep this open and update when/if I get it sorted (or fail lol)

**Comment by carlmontanari** [comment]
@egreenspan2 

Just added `timeout_ops` keyword argument to `send_interactive` methods of generic and network driver. I also "wrapped" the generic driver method w/ the `TimeoutModifier` decorator class -- so now you should be able to pass `timeout_ops=blah` as a keyword w/ the interactive commands. This is only in develop branch right now. You can install develop like:

```
pip install -e git+https://github.com/carlmontanari/scrapli.git@develop#egg=scrapli
```

Let me know if that works for ya!

**Comment by egreenspan2** [comment]
@carlmontanari, forgive my ignorance, how can I install the develop branch for nornir_scrapli? I understand if you don't have time to apply it to that.

Also when I try to set the timeout_ops "manually" in nornir task, channel, it still times out well before an the timeout value I set (3600) and actually times out in about 7 minutes, thrown by multiprocessing_timeout decorator.

2020-12-30 16:28:41,728 - scrapli.channel-<redacted> - INFO - Attempting to send input interact: yes;  expecting: #;   hidden_input: False
2020-12-30 **16:28:41,940** - scrapli.channel-<redacted> - INFO - Read: b'yes'
2020-12-30 **16:35:39,682** - nornir.core.task - ERROR - Host 'redacted': task 'send_interactive' failed with traceback:
Traceback (most recent call last):
  File "/blahblah/.venv/lib64/python3.6/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 640, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

**Comment by carlmontanari** [comment]
Ohhhh I totally did not connect the dots about and realize you are using scrapli via nornir. I will have to get nornir scrapli updated to account for this as well. I'll do that tomorrow morning and will keep ya posted :)

**Comment by carlmontanari** [comment]
Hey again @egreenspan2 

I just pushed a scrapli release to PyPi -- this release contains the timeout modifier on the interactive commands. As for nornir... just pushed a release to develop branch of nornir, you can install it like:

```
pip install -e git+https://github.com/scrapli/nornir_scrapli.git@develop#egg=nornir_scrapli
```

The nornir scrapli develop has the keyword arg `timeout_ops` on the send interactive task. The reason your timeout thing is still happening is (almost certainly) because there is literally nothing coming back from the device during that time. So you also need to change the `timeout_transport` value. Basically `timeout_transport` is the timeout that (with system transport) wraps read/write to the actual transport itself. So if nothing is coming back from the device you will need to crank that up. I'm basically just always setting `timeout_transport` to 0 nowadays and letting `timeout_ops` handle all the timeouts of things (zero will effectively disable the transport timeouts).

Hopefully that makes sense!

Let me know if that sorts you out. If not, and there is still nornir related issues can we close this one down and open an issue w/ the specifics over in nornir_scrapli?

Thanks a bunch, and happy New Years eve!

Carl

**Comment by carlmontanari** [comment]
Hey @egreenspan2 

Hope you had a great New Years! I'm going to go ahead and close this out now as I think this should be resolved. If it isn't for some reason feel free to re-open it, or open an issue over in nornir_scrapli if its more related to that.

Thanks again for raising this!

Carl
