### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by dmfigol** [carlmontanari/scrapli#99]
**Describe the bug**
https://carlmontanari.github.io/scrapli/user_guide/basic_usage/#ssh-config-support -> "Transport notes" 
leads to a broken link

**Comment by carlmontanari** [comment]
Thank you! Went to an old section that was kinda defunct from the original novel-length readme... so removed link but added a blurb w/ I think the relevant info about supported options. 

TL;DR - system ssh does all OpenSSH "stuff", asyncssh (due to asyncssh, nothing scrapli does) also picks up a fair bit of stuff (proxy jump, keys, etc.)... the others I dont believe will do anything automatically so if we had a use case we really cared about (guessing it would be ssh2 related ;)) we could defo look at adding something (like proxy jump or w/e) in!

**Comment by carlmontanari** [comment]
Gunna close, holler if we gotta clean up more stuff!
